language: cpp

sudo: false

compiler:
- clang

addons:
  apt:
    packages:
    - libqt4-dev
    - libqtcore4
    - libqtgui4

before_script:
  - export SOURCE_DIR=$PWD
  - cd /tmp
  - wget https://cmake.org/files/v3.4/cmake-3.4.0-rc3-Linux-x86_64.tar.gz --no-check-certificate
  - tar -xzf cmake-3.4.0-rc3-Linux-x86_64.tar.gz
  - wget https://github.com/martine/ninja/releases/download/v1.6.0/ninja-linux.zip --no-check-certificate
  - unzip ninja-linux.zip
  - wget https://www.orfeo-toolbox.org/srpms/OTB-headers.tar.gz --no-check-certificate
  - chmod +x /tmp/OTB-5.0.0-Linux64.run
  - /tmp/OTB-5.0.0-Linux64.run
  - rm -frv /tmp/OTB-5.0.0-Linux64/lib/{*otb*,*OTB*,applications}
  - rm -frv /tmp/OTB-5.0.0-Linux64/bin
  - cd /tmp/OTB-5.0.0-Linux64/include
  - tar xf /tmp/OTB-headers.tar.gz
  - cd $SOURCE_DIR
  - mkdir build
  - cd build

script: /tmp/cmake-3.4.0-rc3-Linux-x86_64/bin/cmake -DCMAKE_PREFIX_PATH=/tmp/OTB-5.0.0-Linux64 -DCMAKE_INSTALL_PREFIX=../install -DOTB_USE_QT4=OFF -DOTB_USE_CURL=OFF && make
